### ISSUE TITLE
Dodanie kolum DeletedAt/DeletedBy/UpdatedAt (...)

### ISSUE THREAD

**Issue by PrzemyslawKowalskiPK** [PLProjektKompetencyjny/PK_6IO1z_Projekt4_DataBase#17]
Do niektórych tabel rozsądnie będzie dodać kolumny, które:
- będą informować kiedy dany rekord został usunięty/zaktualizowany/utworzony (`DeletedAt/UpdatedAt/CreatedAt`),
- kto dany rekord usunął/zmodyfikował/utworzył (`DeletedBy/UpdatedBy/CreatedBy`).

**Comment by StanislawHorna** [comment]
Plan jest żeby korzystać z triggerów więc raczej nie będzie większych problemów, żeby do każdej tabeli dołożyć drugą z prefixem change_log lub czymś podobnym.

kwestia czy potrzebujemy tak dokładnego info bez zaglądania do dziennika transakcji.

Samo dodanie `DeletedAt/UpdatedAt/CreatedAt` i `DeletedBy/UpdatedBy/CreatedBy` nie będzie stanowić żadnego problemu.
