### ISSUE TITLE
Zmiana konceptu wykonywania operacji

### ISSUE THREAD

**Issue by PrzemyslawKowalskiPK** [PLProjektKompetencyjny/PK_6IO1z_Projekt4_DataBase#30]
Rezerwację traktujemy jako "sklepowy koszyk".
Klient/użytkownik może usunąć pokój z tej rezerwacji lub dodać kolejny pokój.

Czyli w przypadku usunięcia pokoju z rezerwacji w API na back-end'zie jest wykonywany `HttpDelete`.
Analogicznie przy dodaniu pokoju wykonuje się `HttpPost`.

**Comment by StanislawHorna** [comment]
1. Dodać usuwanie rezerwacji **DONE** 👍 
2. Usunąć operację UPDATE do dat na rezerwacji. **DONE** 👍 
3. Dodać weryfikację liczby osób i dostępnych miejsc (łóżek) **DONE** 👍
