### ISSUE TITLE
Wybór silnika bazy danych

### ISSUE THREAD

**Issue by StanislawHorna** [PLProjektKompetencyjny/PK_6IO1z_Projekt4_DataBase#4]
Microsoft SQL, PostgreSQL, a może jeszcze inny?

**Comment by StanislawHorna** [comment]
# Zalety MSSQL
- darmowa wersja SQL Express wystarczy do zrealizowania bazy potrzebnej do projektu
- wszyscy uczestnicy projektu znają T-SQL dzięki przedmiotowi "Bazy Danych" na poprzedni semestrze
- współpracuje z DJango wybranym do budowy Backend'u [here](https://github.com/microsoft/mssql-django)

[Uruchomienie MSSQL w Docker](https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&tabs=cli&pivots=cs1-bash)

**Comment by StanislawHorna** [comment]
# Zalety PostgreSQL
- Open source, włączając użycie komercyjne
- Język PL/Python umożliwia pisanie funkcji PostgreSQL w Python
- Bardzo często spotykane jest spotykane użycie DJango z PostgreSQL

**Comment by PrzemyslawKowalskiPK** [comment]
Wybieramy **PostgresSQL** 🐘 ze względu na **Open source**, większy wachlarz typów danych oraz lepszą skalowalność aplikacji.
